spring:
  profiles: dev
  application :
    name: mall-mybatis-service
  jackson:
    serialization:
      write-dates-as-timestamps: true

#  security:
#    basic:
#      enable: false
#    user:
#      password: root
#      name: root
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.81.219:30003/mall_coupon?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      filters: stat
      max-active: 20
      initial-size: 5
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20

logging:
 level:
  root: INFO
  org.springframework: INFO
  org.mybatis: WARN
  com.jianke.mall: INFO

#健康检查
management:
  server:
    port: 8081
  endpoint:
    health.show-details: always

mybatis-plus:
  #MyBatis 配置文件位置
  #config-location: classpath:mybatis-config.xml
  #MyBatis Mapper 所对应的 XML 文件位置
  #mapper-locations: classpath*:com/jianke/mall/share/mapper/*.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，
  #注册后在 Mapper 对应的 XML 文件中可以直接使用类名，
  #而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  type-aliases-package: com.jianke.demo.entity
  #该配置请和 typeAliasesPackage 一起使用，
  #如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  type-aliases-super-type: java.lang.Object
  #TypeHandler 扫描路径，如果配置了该属性，SqlSessionFactoryBean 会把该包下面的类注册为对应的 TypeHandler。
  #TypeHandler 通常用于自定义类型转换。
  #type-handlers-package: com.jianke.mall.promo.service.handler

  #启动时是否检查 MyBatis XML 文件的存在，默认不检查
  check-config-location: true
    #通过该属性可指定 MyBatis 的执行器，MyBatis 的执行器总共有三种：
    #   ExecutorType.SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句（PreparedStatement）
    #   ExecutorType.REUSE：该执行器类型会复用预处理语句（PreparedStatement）
  #   ExecutorType.BATCH：该执行器类型会批量执行所有的更新语句(配置为batch后在插入在事务中无法获取自增主键)
  #  executor-type: batch
  global-config:
    #是否缓存 Sql 解析，默认不缓存。
    sql-parser-cache: true
    db-config:
      #是否开启 LIKE 查询，即根据 entity 自动生成的 where 条件中 String 类型字段 是否使用 LIKE，默认不开启。
      column-like: false
      db-type: mysql
      #逻辑已删除值,(逻辑删除下有效)
      logic-delete-value: 1
      #逻辑未删除值,(逻辑删除下有效)
      logic-not-delete-value: 0
      #表名前缀
      table-prefix: share_
      #表名、是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true

springfox.documentation.swagger.v2.path: /api-docs
